apiVersion: v1
kind: Service
metadata:
  name: eth-postgresql
  namespace: cc-dev
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
    tier: postgreSQL
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eth-postgresql-claim
  namespace: cc-dev
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-postgresql
  namespace: cc-dev
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: postgreSQL
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:12.4
          name: postgresql
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: ethuser
            - name: POSTGRES_DB
              value: ethereum
            - name: POSTGRES_PASSWORD
              value: BaAUYWsfnSn47vaf4cBuFxrZJ6QHGTLf
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: eth-postgresql-claim
